# 交易系统配置文件
environment = "development"

# 数据库配置
[database]
url = "${DATABASE_URL}"
max_connections = 10
min_connections = 1

# Redis 配置
[redis]
url = "${REDIS_URL}"
pool_size = 10

# 交易所配置
[[exchanges]]
name = "binance"
api_key = "${BINANCE_API_KEY}"
secret_key = "${BINANCE_SECRET_KEY}"
passphrase = ""
sandbox = true
base_url = "https://testnet.binance.vision"

[[exchanges]]
name = "okx"
api_key = "${OKX_API_KEY}"
secret_key = "${OKX_SECRET_KEY}"
passphrase = "${OKX_PASSPHRASE}"
sandbox = true
base_url = "https://www.okx.com"

# 交易配置
[trading]
default_quantity = 0.001
max_position_size = 1.0
risk_percentage = 2.0
enable_trading = false

# 日志配置
[logging]
level = "info"
file_path = "logs/trading.log"

# WebSocket 配置
[websocket]
symbols = ["bnbusdt", "btcusdt", "ethusdt"]
interval = "1s"
auto_reconnect = true
max_retries = 5
retry_delay = 5

# 策略配置
[strategies]
# 移动平均线交叉策略
[strategies.ma_crossover]
enabled = true
short_period = 10
long_period = 20
symbols = ["bnbusdt", "btcusdt"]
min_volume = 1000.0

# RSI 策略
[strategies.rsi_strategy]
enabled = true
period = 14
oversold = 30.0
overbought = 70.0
symbols = ["bnbusdt", "btcusdt"]
min_volume = 1000.0

# 布林带策略
[strategies.bollinger_bands]
enabled = true
period = 20
std_dev = 2.0
symbols = ["bnbusdt", "btcusdt"]
min_volume = 1000.0

# 风控配置
[risk_management]
max_daily_loss = 100.0
max_position_size_per_symbol = 0.1
stop_loss_percentage = 5.0
take_profit_percentage = 10.0
max_open_positions = 5

# 通知配置
[notifications]
telegram_enabled = false
telegram_bot_token = ""
telegram_chat_id = ""
email_enabled = false
email_smtp_server = ""
email_username = ""
email_password = "" 