# WebSocket 配置文件
# 全局基础配置，所有子项都会继承这些设置
[base]
auto_reconnect = true
max_retries = 5
retry_delay_secs = 5
connection_timeout_secs = 10
message_timeout_secs = 30
enable_heartbeat = true
heartbeat_interval_secs = 30
tags = ["default"]

# 标记价格配置
[[mark_price]]
symbol = ["btcusdt"]
interval = "1s"

[[mark_price]]
symbol = ["btcusdt", "ethusdt"]
interval = "1s"

# K线数据配置
[[kline]]
symbol = ["btcusdt"]
interval = "1m"

[[kline]]
symbol = ["btcusdt", "ethusdt"]
interval = "1h"

[[partial_depth]]
symbol = ["turbousdt"]
levels = 10
interval = "500ms"

# 订单簿深度差异配置
[[diff_depth]]
symbol = ["btcusdt"]
level = 5

[[diff_depth]]
symbol = ["btcusdt", "ethusdt"]
level = 10
